version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "06:00"
    open-pull-requests-limit: 3
    labels:
      - "dependencies"
      - "npm"
    ignore:
      - dependency-name: "typescript"
        versions: ["<5.0.0"]
